Add redis payloads
epsagon/otel-js pull request #51
Opened 2022-02-10 12:32 UTC by haddasbronfman

2022-02-10 16:00 UTC, osherv requested changes

2022-02-10 16:09 UTC, haddasbronfman commented on test/instrumentatios/extentions/redis.test.ts
> +instrumentation.disable();
ok. but it makes the span[] from length 2 to 1. 
so I changes it on test: 'test 2 response hooks'

2022-02-10 16:14 UTC, haddasbronfman commented on src/instrumentations/index.ts
> +import { configureRedisnstrumentation as configureRedisInstrumentation } from './extentions/redis';
done

2022-02-14 08:14 UTC, osherv commented on package.json
> +    "redis": "^3.0.0",
Should be dev dependency

2022-02-14 08:16 UTC, osherv commented on src/instrumentations/extentions/redis.ts
> +        span.setAttribute('db.command.response', responseInfo as string);
I think the default behavior should be parse arguments and responses as JSON
And check only for 'multi' case, So if we were missed some commands or new commands were developed we will automatically support them

2022-02-15 08:34 UTC, osherv approved these changes

2022-02-15 08:35 UTC, merged